fix在SSR下document报not defined和引用markers.png图片错误问题
uiwjs/react-baidu-map pull request #131
Opened 2021-05-12 11:31 UTC by haiifeng

在SSR下，修复以下两个问题
1.document报not defined引用错误
2.引用markers.png图片错误问题

2021-05-13 03:13 UTC, jaywcjlove requested changes
图片引入使用 [`next-images`](https://www.npmjs.com/package/next-images) 插件, 不能这么处理

2021-05-13 03:46 UTC, haiifeng commented on src/Marker/useMarker.tsx
> +import defaultIconUrl from 'https://raw.githubusercontent.com/uiwjs/react-baidu-map/master/src/Marker/markers.png';
支持引入图片，要么是直接引入/public/目录下的静态文件，要么是通过require来引入图片(因为是通过服务器来引入的，不是前端直接引入)。
直接用了绝对地址，目前本地开发是没啥问题的。

2021-05-13 04:04 UTC, jaywcjlove commented on src/Marker/useMarker.tsx
> +import defaultIconUrl from 'https://raw.githubusercontent.com/uiwjs/react-baidu-map/master/src/Marker/markers.png';
添加图片支持之后，图片会被编译到静态资源目录中，默认使用本地下载好的百度图片资源。

2021-05-14 16:04 UTC, merged

2021-05-14 16:04 UTC, jaywcjlove commented
@haiifeng 先合并了，但是图片不能这样处理